graph LR


leuCAG(tRNA-Leu-CAG)



leuCAG-->cag1[tRNA-Leu-CAG-1]
leuCAG-->cag2[tRNA-Leu-CAG-2]



cag1-->cag11[tRNA-Leu-CAG-1-1]
cag1-->cag12[tRNA-Leu-CAG-1-2]
cag1-->cag13[tRNA-Leu-CAG-1-3]
cag1-->cag14[tRNA-Leu-CAG-1-4]
cag1-->cag15[tRNA-Leu-CAG-1-5]
cag2-->cag21[tRNA-Leu-CAG-2-1]
cag2-->cag22[tRNA-Leu-CAG-2-2]
cag2-->cag23[tRNA-Leu-CAG-2-3]




style leuCAG fill:MistyRose,stroke:black
style cag1 fill:LightGreen,stroke:black
style cag2 fill:LightBlue,stroke:black
style cag11 fill:HoneyDew,stroke:black
style cag12 fill:HoneyDew,stroke:black
style cag13 fill:HoneyDew,stroke:black
style cag14 fill:HoneyDew,stroke:black
style cag15 fill:HoneyDew,stroke:black
style cag21 fill:AliceBlue,stroke:black
style cag22 fill:AliceBlue,stroke:black
style cag23 fill:AliceBlue,stroke:black