graph LR

subgraph 
mm10(mm10)-->longRNA((longRNA))
longRNA-->pc[Protein coding]
longRNA-->lnc[lncRNA]
mm10-->sRNA((shortRNA))
sRNA-->miRNA[miRNA]
sRNA-->snoRNA[snoRNA]
sRNA-->tRNA((tRNA))
tRNA-->t1((tRNA-Ala))
tRNA-->t1_2(tRNA-Arg)
t1-->t2((tRNA-Ala-AGC))
t1-->t3(tRNA-Ala-CGC)
t2-->t4(tRNA-Ala-AGC-1)
t2-->t5(tRNA-Ala-AGC-2)
t2-->t6(tRNA-Ala-AGC-3)

t6-->seq[...ATGC...]
end

style mm10 fill:MistyRose,stroke:black
style sRNA fill:MistyRose,stroke:black
style tRNA fill:MistyRose,stroke:black
style t1 fill:MistyRose,stroke:black
style t2 fill:MistyRose,stroke:black
style t6 fill:MistyRose,stroke:black
style seq fill:MistyRose,stroke:black